// 샘플 카드 데이터 (30개, 보유 + 판매 통합)
export const sampleCards = [
  // 1–10
  {
    id: 1,
    rarity: 'COMMON',
    category: '풍경',
    owner: '미쓰손',
    description: '우리집 앞마당',
    imageSrc: '/assets/products/photo-card-soldout.svg',
    isSelling: true,
    selling: { price: 4, remaining: 0, outof: 5 },
  },
  {
    id: 2,
    rarity: 'RARE',
    category: '풍경',
    owner: '코드잇',
    description: "How Far I'll Go",
    imageSrc: '/assets/products/photo-card-another.svg',
    isSelling: true,
    selling: { price: 4, remaining: 1, outof: 5 },
  },
  {
    id: 3,
    rarity: 'SUPER RARE',
    category: '여행',
    owner: '코드잇덕후',
    description: '스페인 여행',
    imageSrc: '/assets/products/photo-card-two.svg',
    isSelling: true,
    selling: { price: 4, remaining: 2, outof: 5 },
  },
  {
    id: 4,
    rarity: 'COMMON',
    category: '풍경',
    owner: '코드잇',
    description: '한강 노을',
    imageSrc: '/assets/products/photo-card-another.svg',
    isSelling: false,
    selling: null,
  },
  {
    id: 5,
    rarity: 'LEGENDARY',
    category: '풍경',
    owner: '미쓰손',
    description: '알프스 설산',
    imageSrc: '/assets/products/photo-card-soldout.svg',
    isSelling: true,
    selling: { price: 10, remaining: 0, outof: 5 },
  },
  {
    id: 6,
    rarity: 'RARE',
    category: '여행',
    owner: '미쓰손',
    description: '도쿄 야경',
    imageSrc: '/assets/products/photo-card-another.svg',
    isSelling: true,
    selling: { price: 5, remaining: 1, outof: 5 },
  },
  {
    id: 7,
    rarity: 'COMMON',
    category: '여행',
    owner: '코드잇',
    description: '부산 바다',
    imageSrc: '/assets/products/photo-card-another.svg',
    isSelling: false,
    selling: null,
  },
  {
    id: 8,
    rarity: 'SUPER RARE',
    category: '여행',
    owner: '코드잇덕후',
    description: '파리 에펠탑',
    imageSrc: '/assets/products/photo-card-two.svg',
    isSelling: true,
    selling: { price: 6, remaining: 1, outof: 5 },
  },
  {
    id: 9,
    rarity: 'RARE',
    category: '풍경',
    owner: '코드잇덕후',
    description: '가을 숲길',
    imageSrc: '/assets/products/photo-card-another.svg',
    isSelling: false,
    selling: null,
  },
  {
    id: 10,
    rarity: 'LEGENDARY',
    category: '풍경',
    owner: '미쓰손',
    description: '사막의 별',
    imageSrc: '/assets/products/photo-card-soldout.svg',
    isSelling: true,
    selling: { price: 10, remaining: 0, outof: 5 },
  },

  // 11–20
  {
    id: 11,
    rarity: 'COMMON',
    category: '풍경',
    owner: '미쓰손',
    description: '비 오는 창가',
    imageSrc: '/assets/products/photo-card-another.svg',
    isSelling: false,
    selling: null,
  },
  {
    id: 12,
    rarity: 'RARE',
    category: '여행',
    owner: '코드잇',
    description: '이탈리아 골목',
    imageSrc: '/assets/products/photo-card-another.svg',
    isSelling: true,
    selling: { price: 5, remaining: 2, outof: 5 },
  },
  {
    id: 13,
    rarity: 'SUPER RARE',
    category: '여행',
    owner: '미쓰손',
    description: '뉴욕 타임스퀘어',
    imageSrc: '/assets/products/photo-card-two.svg',
    isSelling: true,
    selling: { price: 6, remaining: 1, outof: 5 },
  },
  {
    id: 14,
    rarity: 'COMMON',
    category: '풍경',
    owner: '코드잇',
    description: '초여름 들판',
    imageSrc: '/assets/products/photo-card-another.svg',
    isSelling: false,
    selling: null,
  },
  {
    id: 15,
    rarity: 'RARE',
    category: '풍경',
    owner: '미쓰손',
    description: '노을진 골목',
    imageSrc: '/assets/products/photo-card-another.svg',
    isSelling: true,
    selling: { price: 4, remaining: 3, outof: 5 },
  },
  {
    id: 16,
    rarity: 'SUPER RARE',
    category: '여행',
    owner: '코드잇덕후',
    description: '아이슬란드 빙하',
    imageSrc: '/assets/products/photo-card-two.svg',
    isSelling: false,
    selling: null,
  },
  {
    id: 17,
    rarity: 'COMMON',
    category: '여행',
    owner: '코드잇',
    description: '제주 오름',
    imageSrc: '/assets/products/photo-card-another.svg',
    isSelling: true,
    selling: { price: 3, remaining: 4, outof: 5 },
  },
  {
    id: 18,
    rarity: 'LEGENDARY',
    category: '풍경',
    owner: '코드잇덕후',
    description: '히말라야 설산',
    imageSrc: '/assets/products/photo-card-soldout.svg',
    isSelling: true,
    selling: { price: 12, remaining: 0, outof: 5 },
  },
  {
    id: 19,
    rarity: 'RARE',
    category: '풍경',
    owner: '미쓰손',
    description: '겨울 호수',
    imageSrc: '/assets/products/photo-card-another.svg',
    isSelling: false,
    selling: null,
  },
  {
    id: 20,
    rarity: 'COMMON',
    category: '풍경',
    owner: '코드잇',
    description: '도심 야경',
    imageSrc: '/assets/products/photo-card-another.svg',
    isSelling: false,
    selling: null,
  },

  // 21–30
  {
    id: 21,
    rarity: 'RARE',
    category: '여행',
    owner: '코드잇덕후',
    description: '런던 브릿지',
    imageSrc: '/assets/products/photo-card-another.svg',
    isSelling: true,
    selling: { price: 5, remaining: 2, outof: 5 },
  },
  {
    id: 22,
    rarity: 'SUPER RARE',
    category: '풍경',
    owner: '미쓰손',
    description: '별이 쏟아지는 밤',
    imageSrc: '/assets/products/photo-card-two.svg',
    isSelling: false,
    selling: null,
  },
  {
    id: 23,
    rarity: 'COMMON',
    category: '여행',
    owner: '코드잇',
    description: '강릉 바다',
    imageSrc: '/assets/products/photo-card-another.svg',
    isSelling: true,
    selling: { price: 3, remaining: 5, outof: 5 },
  },
  {
    id: 24,
    rarity: 'RARE',
    category: '풍경',
    owner: '미쓰손',
    description: '안개 낀 숲',
    imageSrc: '/assets/products/photo-card-another.svg',
    isSelling: false,
    selling: null,
  },
  {
    id: 25,
    rarity: 'LEGENDARY',
    category: '여행',
    owner: '코드잇덕후',
    description: '마추픽추',
    imageSrc: '/assets/products/photo-card-soldout.svg',
    isSelling: true,
    selling: { price: 15, remaining: 0, outof: 5 },
  },
  {
    id: 26,
    rarity: 'COMMON',
    category: '풍경',
    owner: '코드잇',
    description: '봄 벚꽃길',
    imageSrc: '/assets/products/photo-card-another.svg',
    isSelling: false,
    selling: null,
  },
  {
    id: 27,
    rarity: 'RARE',
    category: '여행',
    owner: '미쓰손',
    description: '베를린 거리',
    imageSrc: '/assets/products/photo-card-another.svg',
    isSelling: true,
    selling: { price: 6, remaining: 1, outof: 5 },
  },
  {
    id: 28,
    rarity: 'SUPER RARE',
    category: '풍경',
    owner: '코드잇덕후',
    description: '오로라',
    imageSrc: '/assets/products/photo-card-two.svg',
    isSelling: false,
    selling: null,
  },
  {
    id: 29,
    rarity: 'COMMON',
    category: '여행',
    owner: '코드잇',
    description: '산토리니 해변',
    imageSrc: '/assets/products/photo-card-another.svg',
    isSelling: true,
    selling: { price: 4, remaining: 2, outof: 5 },
  },
  {
    id: 30,
    rarity: 'LEGENDARY',
    category: '풍경',
    owner: '미쓰손',
    description: '빙하 호수',
    imageSrc: '/assets/products/photo-card-soldout.svg',
    isSelling: true,
    selling: { price: 14, remaining: 0, outof: 5 },
  },
  {
    id: 31,
    rarity: 'COMMON',
    category: '풍경',
    owner: '미쓰손',
    description: '새벽 안개 들판',
    imageSrc: '/assets/products/photo-card-another.svg',
    isSelling: false,
    selling: null,
  },
  {
    id: 32,
    rarity: 'RARE',
    category: '여행',
    owner: '코드잇',
    description: '리스본 트램',
    imageSrc: '/assets/products/photo-card-another.svg',
    isSelling: true,
    selling: { price: 5, remaining: 3, outof: 5 },
  },
  {
    id: 33,
    rarity: 'SUPER RARE',
    category: '풍경',
    owner: '코드잇덕후',
    description: '은하수 밤하늘',
    imageSrc: '/assets/products/photo-card-two.svg',
    isSelling: true,
    selling: { price: 7, remaining: 2, outof: 5 },
  },
  {
    id: 34,
    rarity: 'COMMON',
    category: '여행',
    owner: '미쓰손',
    description: '남해 바닷길',
    imageSrc: '/assets/products/photo-card-another.svg',
    isSelling: true,
    selling: { price: 3, remaining: 5, outof: 5 },
  },
  {
    id: 35,
    rarity: 'LEGENDARY',
    category: '풍경',
    owner: '코드잇',
    description: '폭풍우 치는 절벽',
    imageSrc: '/assets/products/photo-card-soldout.svg',
    isSelling: true,
    selling: { price: 16, remaining: 0, outof: 5 },
  },
  {
    id: 36,
    rarity: 'RARE',
    category: '풍경',
    owner: '미쓰손',
    description: '노란 유채꽃밭',
    imageSrc: '/assets/products/photo-card-another.svg',
    isSelling: false,
    selling: null,
  },
  {
    id: 37,
    rarity: 'SUPER RARE',
    category: '여행',
    owner: '코드잇덕후',
    description: '사하라 사막 일몰',
    imageSrc: '/assets/products/photo-card-two.svg',
    isSelling: true,
    selling: { price: 8, remaining: 1, outof: 5 },
  },
  {
    id: 38,
    rarity: 'COMMON',
    category: '풍경',
    owner: '코드잇',
    description: '비 오는 골목길',
    imageSrc: '/assets/products/photo-card-another.svg',
    isSelling: false,
    selling: null,
  },
  {
    id: 39,
    rarity: 'RARE',
    category: '여행',
    owner: '미쓰손',
    description: '프라하 구시가지',
    imageSrc: '/assets/products/photo-card-another.svg',
    isSelling: true,
    selling: { price: 6, remaining: 2, outof: 5 },
  },
  {
    id: 40,
    rarity: 'LEGENDARY',
    category: '여행',
    owner: '코드잇덕후',
    description: '남극 빙산',
    imageSrc: '/assets/products/photo-card-soldout.svg',
    isSelling: true,
    selling: { price: 18, remaining: 0, outof: 5 },
  },
];
